addSbtPlugin("org.jetbrains"    % "sbt-ide-settings"    % "1.1.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.9.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.0")
addSbtPlugin("com.heroku"       % "sbt-heroku"          % "2.1.3")
